server {
    listen 80;
    server_name localhost; # En prod, ce sera api.fadel.td

    location / {
        proxy_pass http://fadel_backend:3000; # Redirige vers le service 'backend' du docker-compose
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Configuration pour le Swagger (Documentation)
    location /api-docs {
        proxy_pass http://fadel_backend:3000/api-docs;
    }
}